eleve:
    path:     /
    defaults: { _controller: "GestyGestyBundle:Eleve:index" }

eleve_show:
    path:     /{id}/show
    defaults: { _controller: "GestyGestyBundle:Eleve:show" }

eleve_new:
    path:     /new
    defaults: { _controller: "GestyGestyBundle:Eleve:new" }

eleve_create:
    path:     /create
    defaults: { _controller: "GestyGestyBundle:Eleve:create" }
    methods:  POST

eleve_edit:
    path:     /{id}/edit
    defaults: { _controller: "GestyGestyBundle:Eleve:edit" }

eleve_update:
    path:     /{id}/update
    defaults: { _controller: "GestyGestyBundle:Eleve:update" }
    methods:  [POST, PUT]

eleve_delete:
    path:     /{id}/delete
    defaults: { _controller: "GestyGestyBundle:Eleve:delete" }
    methods:  [POST, DELETE]
